# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# def index
#     # @products = Product.all
#     @query = params['query']
#     render :json => {
#         "products"=> Product.where('name ILIKE ?', "%#{@query}%" )
#     }
#   end

product_list = [
    [1, 'Bread Base - Toscano', '$4.32', 'synergize impactful mindshare'],
    [2, 'Cheese - Cheddar With Claret', '$9.09', 'incentivize efficient deliverables'],
    [3, 'Flour - Teff', '$4.77', 'morph front-end ROI'],
    [4, 'Jameson Irish Whiskey', '$8.80', 'scale real-time synergies'],
    [5, 'Kippers - Smoked', '$6.78', 'incentivize magnetic experiences'],
    [6, 'Oneshot Automatic Soap System', '$5.22', 'transition plug-and-play infomediaries'],
    [7, 'Lamb - Leg, Diced', '$2.21', 'target 24/365 e-business'],
    [8, 'Arrowroot', '$3.36', 'engineer holistic relationships'],
    [9, 'Mustard - Individual Pkg', '$2.05', 'expedite global eyeballs'],
    [10, 'The Pop Shoppe - Lime Rickey', '$4.56', 'unleash proactive bandwidth'],
    [11, 'Tuna - Sushi Grade', '$8.65', 'synergize leading-edge bandwidth'],
    [12, 'Water - Spring Water 500ml', '$9.04', 'whiteboard ubiquitous eyeballs'],
    [13, 'Icecream - Dstk Cml And Fdg', '$4.35', 'expedite holistic relationships'],
    [14, 'Bay Leaf Ground', '$4.17', 'evolve out-of-the-box mindshare'],
    [15, 'Cookies - Oreo, 4 Pack', '$4.64', 'engineer synergistic portals'],
    [16, 'Flour - Bran, Red', '$9.61', 'transform sexy content'],
    [17, 'Bok Choy - Baby', '$9.62', 'expedite virtual interfaces'],
    [18, 'Container Clear 8 Oz', '$2.12', 'seize dot-com e-commerce'],
    [19, 'Bread Roll Foccacia', '$5.87', 'implement enterprise action-items'],
    [20, 'Olives - Stuffed', '$1.88', 'maximize next-generation interfaces'],
    [21, 'Apricots - Dried', '$6.30', 'deliver world-class markets'],
    [22, 'Towel Dispenser', '$6.08', 'empower open-source schemas'],
    [23, 'Beets', '$4.57', 'drive scalable relationships'],
    [24, 'Orange - Tangerine', '$3.36', 'orchestrate wireless networks'],
    [25, 'Puree - Pear', '$1.60', 'disintermediate B2B supply-chains'],
    [26, 'Smoked Tongue', '$2.03', 'leverage e-business models'],
    [27, 'Pecan Raisin - Tarts', '$1.90', 'transition vertical web-readiness'],
    [28, 'Container - Clear 16 Oz', '$6.28', 'whiteboard mission-critical users'],
    [29, 'Beef - Tenderloin - Aa', '$4.48', 'seize collaborative architectures'],
    [30, 'Bar - Sweet And Salty Chocolate', '$9.48', 'innovate vertical markets'],
    [31, 'Steamers White', '$1.97', 'envisioneer collaborative communities'],
    [32, 'Pea - Snow', '$6.41', 'synthesize user-centric web-readiness'],
    [33, 'Lidsoupcont Rp12dn', '$1.71', 'synergize B2B functionalities'],
    [34, 'Durian Fruit', '$7.28', 'scale rich niches'],
    [35, 'Buffalo - Short Rib Fresh', '$5.30', 'innovate back-end web services'],
    [36, 'Haggis', '$7.04', 'redefine real-time ROI'],
    [37, 'Pasta - Ravioli', '$8.68', 'target strategic mindshare'],
    [38, 'Ezy Change Mophandle', '$4.69', 'engineer leading-edge applications'],
    [39, 'Bread - Raisin', '$3.16', 'whiteboard clicks-and-mortar applications'],
    [40, 'Sausage - Meat', '$5.44', 'optimize e-business eyeballs'],
    [41, 'Beef - Montreal Smoked Brisket', '$8.01', 'optimize sticky content'],
    [42, 'Pork Salted Bellies', '$1.35', 'incubate frictionless functionalities'],
    [43, 'Fish - Base, Bouillion', '$9.47', 'revolutionize seamless solutions'],
    [44, 'Cheese - Brie, Triple Creme', '$5.07', 'transition sticky synergies'],
    [45, 'Beef - Chuck, Boneless', '$7.37', 'grow collaborative models'],
    [46, 'Wine - Redchard Merritt', '$2.81', 'monetize rich systems'],
    [47, 'Coffee - Irish Cream', '$7.19', 'matrix plug-and-play metrics'],
    [48, 'Veal - Tenderloin, Untrimmed', '$4.98', 'matrix integrated models'],
    [49, 'Trueblue - Blueberry 12x473ml', '$1.22', 'mesh frictionless content'],
    [50, 'Papadam', '$5.53', 'deliver web-enabled markets'],
    [51, 'Oil - Canola', '$5.77', 'orchestrate interactive architectures'],
    [52, 'Tomatoes - Orange', '$8.96', 'productize bleeding-edge solutions'],
    [53, 'Onions - Cippolini', '$9.39', 'expedite granular systems'],
    [54, 'Pasta - Bauletti, Chicken White', '$5.05', 'visualize open-source metrics'],
    [55, 'Sobe - Tropical Energy', '$9.04', 'incubate 24/7 markets'],
    [56, 'Chips Potato Salt Vinegar 43g', '$9.24', 'utilize visionary markets'],
    [57, 'Carbonated Water - Lemon Lime', '$7.43', 'morph viral systems'],
    [58, 'Star Fruit', '$8.73', 'recontextualize cutting-edge paradigms'],
    [59, 'Muffin - Mix - Mango Sour Cherry', '$6.44', 'leverage dot-com action-items'],
    [60, 'Muffin Hinge - 211n', '$9.96', 'repurpose interactive action-items'],
    [61, 'Pie Pecan', '$2.09', 'expedite dynamic synergies'],
    [62, 'Beef - Rib Roast, Cap On', '$4.35', 'e-enable bricks-and-clicks eyeballs'],
    [63, 'Ham - Smoked, Bone - In', '$6.42', 'expedite bricks-and-clicks interfaces'],
    [64, 'Nut - Pumpkin Seeds', '$1.12', 'transition magnetic convergence'],
    [65, 'Tea - Herbal Orange Spice', '$8.15', 'morph ubiquitous schemas'],
    [66, 'Tea - Lemon Scented', '$9.70', 'synthesize open-source portals'],
    [67, 'Emulsifier', '$7.98', 'synthesize interactive experiences'],
    [68, 'Grapefruit - Pink', '$7.00', 'optimize rich deliverables'],
    [69, 'Tomatoes - Vine Ripe, Red', '$3.88', 'architect intuitive architectures'],
    [70, 'Soup - Cream Of Broccoli', '$3.88', 'orchestrate e-business vortals'],
    [71, 'Oyster - In Shell', '$1.80', 'architect holistic systems'],
    [72, 'Cinnamon - Stick', '$2.42', 'integrate value-added niches'],
    [73, 'Cheese - Montery Jack', '$2.90', 'implement scalable convergence'],
    [74, 'Wine - Stoneliegh Sauvignon', '$3.16', 'drive enterprise architectures'],
    [75, 'Shallots', '$2.88', 'matrix web-enabled channels'],
    [76, 'Coffee - Decafenated', '$1.39', 'implement distributed metrics'],
    [77, 'Loaf Pan - 2 Lb, Foil', '$4.42', 'leverage visionary relationships'],
    [78, 'Salt And Pepper Mix - Black', '$6.83', 'orchestrate end-to-end niches'],
    [79, 'Coffee - Dark Roast', '$7.18', 'extend enterprise e-services'],
    [80, 'Paper Cocktail Umberlla 80 - 180', '$3.59', 'implement magnetic e-services'],
    [81, 'Cheese - Cheddar, Mild', '$9.60', 'empower 24/365 communities'],
    [82, 'Beans - Fine', '$1.47', 'embrace end-to-end communities'],
    [83, 'Potatoes - Idaho 100 Count', '$5.65', 'repurpose open-source supply-chains'],
    [84, 'Ecolab - Orange Frc, Cleaner', '$4.23', 'implement transparent markets'],
    [85, 'Liners - Baking Cups', '$9.34', 'optimize global platforms'],
    [86, 'Cinnamon Rolls', '$3.06', 'target seamless e-markets'],
    [87, 'Pike - Frozen Fillet', '$8.59', 'streamline front-end interfaces'],
    [88, 'Pepper - Red Chili', '$7.52', 'synthesize end-to-end users'],
    [89, 'Basil - Pesto Sauce', '$9.95', 'implement seamless eyeballs'],
    [90, 'Scallops - Live In Shell', '$3.71', 'embrace sexy channels'],
    [91, 'Doilies - 10, Paper', '$6.12', 'deliver rich solutions'],
    [92, 'Shark - Loin', '$1.95', 'matrix B2B platforms'],
    [93, 'Beef - Texas Style Burger', '$3.47', 'empower revolutionary architectures'],
    [94, 'Chef Hat 20cm', '$4.57', 'synergize user-centric infrastructures'],
    [95, 'Shrimp - Baby, Warm Water', '$4.76', 'incentivize customized channels'],
    [96, 'Chicken Breast Wing On', '$4.89', 'revolutionize ubiquitous web-readiness'],
    [97, 'Snapple - Mango Maddness', '$4.61', 'expedite B2B e-tailers'],
    [98, 'Ostrich - Prime Cut', '$4.87', 'scale open-source users'],
    [99, 'Beef - Tongue, Fresh', '$4.71', 'harness revolutionary content'],
    [100, 'Figs', '$2.16', 'visualize rich web-readiness'],
    [101, 'Island Oasis - Banana Daiquiri', '$3.30', 'monetize dynamic channels'],
    [102, 'Oregano - Dry, Rubbed', '$1.09', 'strategize magnetic web services'],
    [103, 'Southern Comfort', '$6.07', 'harness killer e-services'],
    [104, 'Wine - Soave Folonari', '$7.01', 'synthesize virtual mindshare'],
    [105, 'Dc - Frozen Momji', '$6.35', 'brand vertical e-markets'],
    [106, 'Ecolab - Lime - A - Way 4/4 L', '$9.62', 'seize mission-critical metrics'],
    [107, 'Pork - Bones', '$5.13', 'deploy distributed applications'],
    [108, 'Leeks - Large', '$1.30', 'innovate granular solutions'],
    [109, 'Cheese - St. Andre', '$7.09', 'evolve bricks-and-clicks bandwidth'],
    [110, 'Wine - Fat Bastard Merlot', '$2.97', 'productize compelling infomediaries'],
    [111, 'Milk Powder', '$4.08', 'e-enable killer deliverables'],
    [112, 'Pepper - Orange', '$2.14', 'optimize turn-key e-markets'],
    [113, 'Bread - White, Sliced', '$9.11', 'morph proactive markets'],
    [114, 'Mushroom - Trumpet, Dry', '$6.16', 'benchmark clicks-and-mortar deliverables'],
    [115, 'Glove - Cutting', '$8.38', 'envisioneer user-centric infrastructures'],
    [116, 'Seedlings - Buckwheat, Organic', '$9.61', 'aggregate real-time paradigms'],
    [117, 'Muffin Mix - Morning Glory', '$5.71', 'visualize scalable interfaces'],
    [118, 'Beans - Black Bean, Dry', '$5.24', 'enhance front-end channels'],
    [119, 'Apple - Custard', '$2.76', 'extend e-business web services'],
    [120, 'Salsify, Organic', '$7.32', 'benchmark visionary interfaces'],
    [121, 'Beer - Upper Canada Light', '$2.16', 'implement dynamic convergence'],
    [122, 'English Muffin', '$2.35', 'syndicate scalable systems'],
    [123, 'Pepper - White, Ground', '$4.44', 'scale strategic content'],
    [124, 'Food Colouring - Green', '$1.30', 'target leading-edge content'],
    [125, 'Vinegar - Cider', '$1.12', 'morph cross-media e-business'],
    [126, 'Veal - Inside Round / Top, Lean', '$9.43', 'reintermediate vertical e-markets'],
    [127, 'Lamb - Shoulder, Boneless', '$6.81', 'visualize front-end solutions'],
    [128, 'Gelatine Leaves - Bulk', '$2.20', 'aggregate plug-and-play initiatives'],
    [129, 'Kiwi', '$6.49', 'iterate efficient e-tailers'],
    [130, 'Muffin Mix - Banana Nut', '$2.72', 'implement clicks-and-mortar e-markets'],
    [131, 'Soup Campbells Turkey Veg.', '$8.21', 'deliver real-time initiatives'],
    [132, 'Scallops - 20/30', '$1.14', 'incentivize 24/7 platforms'],
    [133, 'Coffee - Beans, Whole', '$2.56', 'grow customized web services'],
    [134, 'Leeks - Large', '$1.20', 'engineer collaborative synergies'],
    [135, 'Ocean Spray - Ruby Red', '$1.22', 'strategize next-generation e-business'],
    [136, 'Contreau', '$8.17', 'target next-generation action-items'],
    [137, 'Beans - Butter Lrg Lima', '$6.74', 'e-enable vertical systems'],
    [138, 'Wine - Chianti Classico Riserva', '$6.85', 'implement real-time mindshare'],
    [139, 'Coffee - Espresso', '$9.16', 'envisioneer distributed e-markets'],
    [140, 'Pasta - Linguini, Dry', '$5.63', 'seize collaborative web services'],
    [141, 'Sauce - Sesame Thai Dressing', '$5.66', 'benchmark transparent schemas'],
    [142, 'Towel Multifold', '$4.40', 'transform sexy solutions'],
    [143, 'Containter - 3oz Microwave Rect.', '$6.14', 'innovate integrated niches'],
    [144, 'Muffin - Carrot Individual Wrap', '$7.24', 'drive granular markets'],
    [145, 'Sour Puss Raspberry', '$6.99', 'optimize granular functionalities'],
    [146, 'Wine La Vielle Ferme Cote Du', '$3.12', 'incentivize transparent communities'],
    [147, 'Mortadella', '$1.80', 'engineer vertical ROI'],
    [148, 'Bread - Bistro Sour', '$3.19', 'incentivize rich architectures'],
    [149, 'Sausage - Blood Pudding', '$7.62', 'e-enable cross-media e-markets'],
    [150, 'Munchies Honey Sweet Trail Mix', '$4.50', 'synthesize virtual e-services'],
    [151, 'Wine - Periguita Fonseca', '$3.73', 'redefine enterprise models'],
    [152, 'Truffle Cups - White Paper', '$4.33', 'synergize cross-media mindshare'],
    [153, 'Tea Peppermint', '$5.34', 'transition one-to-one technologies'],
    [154, 'Island Oasis - Pina Colada', '$1.11', 'reintermediate scalable paradigms'],
    [155, 'Ice Cream Bar - Hagen Daz', '$9.94', 'architect turn-key experiences'],
    [156, 'Wine - Barbera Alba Doc 2001', '$1.07', 'incentivize cross-platform action-items'],
    [157, 'Soup - Campbells, Creamy', '$4.30', 'whiteboard back-end infomediaries'],
    [158, 'Cake Sheet Combo Party Pack', '$5.36', 'drive scalable technologies'],
    [159, 'Bagelers - Cinn / Brown', '$8.04', 'recontextualize cross-platform convergence'],
    [160, 'Cabbage - Nappa', '$8.19', 'repurpose vertical mindshare'],
    [161, 'Juice - Ocean Spray Kiwi', '$6.80', 'scale real-time networks'],
    [162, 'Rosemary - Fresh', '$1.01', 'repurpose cross-platform channels'],
    [163, 'Doilies - 5, Paper', '$3.32', 'empower vertical e-tailers'],
    [164, 'Coconut - Whole', '$3.65', 'transform seamless schemas'],
    [165, 'Bar Bran Honey Nut', '$6.92', 'optimize collaborative web-readiness'],
    [166, 'Everfresh Products', '$5.99', 'empower rich e-tailers'],
    [167, 'Fond - Chocolate', '$9.33', 'matrix sexy schemas'],
    [168, 'Ecolab Silver Fusion', '$1.32', 'disintermediate 24/365 action-items'],
    [169, 'Soda Water - Club Soda, 355 Ml', '$6.58', 'monetize value-added methodologies'],
    [170, 'Soup - Campbells Tomato Ravioli', '$5.34', 'deliver next-generation infomediaries'],
    [171, 'Pasta - Fett Alfredo, Single Serve', '$2.24', 'evolve proactive mindshare'],
    [172, 'Dried Cranberries', '$3.80', 'engineer proactive relationships'],
    [173, 'Pie Filling - Cherry', '$2.30', 'orchestrate visionary infomediaries'],
    [174, 'Lamb - Shoulder, Boneless', '$9.92', 'deploy collaborative e-markets'],
    [175, 'Bread - Burger', '$6.91', 'expedite dot-com bandwidth'],
    [176, 'Gherkin - Sour', '$7.89', 'transform intuitive architectures'],
    [177, 'Wine - White, Mosel Gold', '$8.97', 'streamline real-time networks'],
    [178, 'Wine - Sherry Dry Sack, William', '$1.47', 'incentivize B2C infrastructures'],
    [179, 'Vinegar - Rice', '$4.82', 'reinvent B2B web-readiness'],
    [180, 'Turkey - Breast, Boneless Sk On', '$7.84', 'synergize efficient eyeballs'],
    [181, 'Veal - Bones', '$4.78', 'exploit bricks-and-clicks solutions'],
    [182, 'Guava', '$3.37', 'architect one-to-one users'],
    [183, 'Cheese - Victor Et Berthold', '$6.20', 'orchestrate visionary networks'],
    [184, 'Eel Fresh', '$8.91', 'unleash plug-and-play e-tailers'],
    [185, 'Pork - Loin, Boneless', '$1.77', 'unleash best-of-breed ROI'],
    [186, 'Pepper - Sorrano', '$4.08', 'maximize mission-critical deliverables'],
    [187, 'Bagelers - Cinn / Brown', '$3.42', 'benchmark 24/365 synergies'],
    [188, 'Nut - Almond, Blanched, Ground', '$1.90', 'matrix one-to-one ROI'],
    [189, 'Icecream - Dibs', '$8.66', 'exploit revolutionary users'],
    [190, 'Tart - Raisin And Pecan', '$5.58', 'drive synergistic deliverables'],
    [191, 'Pail - 4l White, With Handle', '$8.11', 'drive plug-and-play schemas'],
    [192, 'Coffee - Almond Amaretto', '$8.14', 'benchmark B2B interfaces'],
    [193, 'Juice - Pineapple, 48 Oz', '$2.71', 'synthesize ubiquitous networks'],
    [194, 'Bagelers - Cinn / Brown', '$3.27', 'utilize end-to-end networks'],
    [195, 'Juice - Cranberry 284ml', '$6.22', 'aggregate bleeding-edge mindshare'],
    [196, 'Flour - So Mix Cake White', '$3.65', 'evolve web-enabled networks'],
    [197, 'Miso Paste White', '$5.70', 'envisioneer 24/7 architectures'],
    [198, 'Wine - Niagara,vqa Reisling', '$9.84', 'enhance value-added ROI'],
    [199, 'Nantucket Orange Juice', '$5.78', 'envisioneer bleeding-edge web-readiness'],
    [200, 'Wine - Red, Gamay Noir', '$7.40', 'monetize customized methodologies'],
    [201, 'Tomatoes - Vine Ripe, Red', '$8.66', 'orchestrate impactful partnerships'],
    [202, 'Sausage - Meat', '$6.87', 'transform bleeding-edge portals'],
    [203, 'Jam - Raspberry', '$9.44', 'envisioneer scalable portals'],
    [204, 'Shrimp - Tiger 21/25', '$6.63', 'benchmark magnetic e-business'],
    [205, 'C - Plus, Orange', '$2.90', 'incubate back-end vortals'],
    [206, 'Chinese Foods - Cantonese', '$4.33', 'facilitate B2C systems'],
    [207, 'Blueberries - Frozen', '$7.07', 'mesh customized initiatives'],
    [208, 'Beer - Steamwhistle', '$6.50', 'leverage leading-edge infrastructures'],
    [209, 'Wine - Chardonnay South', '$2.42', 'leverage visionary users'],
    [210, 'Oats Large Flake', '$9.93', 'strategize interactive experiences'],
    [211, 'Ice Cream Bar - Hageen Daz To', '$4.19', 'exploit killer markets'],
    [212, 'Bread - Sour Sticks With Onion', '$7.46', 'enhance clicks-and-mortar interfaces'],
    [213, 'Mortadella', '$1.66', 'synergize cutting-edge interfaces'],
    [214, 'Oxtail - Cut', '$2.37', 'expedite scalable e-services'],
    [215, 'Cookies - Amaretto', '$5.84', 'incentivize out-of-the-box action-items'],
    [216, 'Wine - Red, Metus Rose', '$3.42', 'revolutionize cross-platform experiences'],
    [217, 'Flavouring Vanilla Artificial', '$5.06', 'optimize customized methodologies'],
    [218, 'Chocolate Bar - Smarties', '$7.93', 'envisioneer distributed infrastructures'],
    [219, 'Icecream - Dibs', '$8.13', 'innovate web-enabled e-markets'],
    [220, 'Gooseberry', '$6.76', 'empower next-generation schemas'],
    [221, 'Pasta - Cappellini, Dry', '$3.34', 'facilitate viral partnerships'],
    [222, 'Napkin - Beverge, White 2 - Ply', '$7.13', 'streamline end-to-end deliverables'],
    [223, 'Spice - Greek 1 Step', '$5.28', 'engineer wireless initiatives'],
    [224, 'Trout Rainbow Whole', '$9.52', 'strategize dot-com methodologies'],
    [225, 'Tea - Vanilla Chai', '$3.57', 'e-enable scalable partnerships'],
    [226, 'Flour - Corn, Fine', '$9.48', 'incentivize ubiquitous bandwidth'],
    [227, 'Shrimp - Baby, Warm Water', '$3.91', 'engage rich initiatives'],
    [228, 'Mushroom - White Button', '$7.61', 'reintermediate 24/365 systems'],
    [229, 'Stainless Steel Cleaner Vision', '$9.89', 'innovate web-enabled markets'],
    [230, 'Olive - Spread Tapenade', '$9.10', 'facilitate magnetic eyeballs'],
    [231, 'White Baguette', '$9.65', 'recontextualize cross-platform portals'],
    [232, 'Beans - Black Bean, Canned', '$1.88', 'recontextualize next-generation ROI'],
    [233, 'Wine - Toasted Head', '$5.01', 'leverage open-source applications'],
    [234, 'Pike - Frozen Fillet', '$6.46', 'seize interactive convergence'],
    [235, 'Salmon - Atlantic, No Skin', '$2.82', 'unleash strategic architectures'],
    [236, 'Wine - Chianti Classica Docg', '$1.75', 'exploit vertical deliverables'],
    [237, 'Potatoes - Peeled', '$1.86', 'e-enable robust experiences'],
    [238, 'Apple - Delicious, Red', '$7.74', 'disintermediate strategic infrastructures'],
    [239, 'Fenngreek Seed', '$6.65', 'seize value-added infrastructures'],
    [240, 'Wine - Blue Nun Qualitatswein', '$9.25', 'synergize best-of-breed users'],
    [241, 'Flower - Commercial Bronze', '$1.35', 'iterate killer solutions'],
    [242, 'Wine - White, Pinot Grigio', '$5.62', 'implement plug-and-play markets'],
    [243, 'Chilli Paste, Sambal Oelek', '$5.01', 'engage integrated paradigms'],
    [244, 'Scrubbie - Scotchbrite Hand Pad', '$8.08', 'mesh impactful content'],
    [245, 'Creme De Menthe Green', '$2.11', 'scale virtual portals'],
    [246, 'Chocolate Bar - Oh Henry', '$5.99', 'unleash bleeding-edge convergence'],
    [247, 'Coconut Milk - Unsweetened', '$2.19', 'envisioneer robust markets'],
    [248, 'Trout - Rainbow, Frozen', '$4.13', 'productize magnetic channels'],
    [249, 'Soup - Campbells Beef Strogonoff', '$5.11', 'embrace customized convergence'],
    [250, 'Glass Clear 8 Oz', '$4.84', 'expedite visionary eyeballs'],
    [251, 'Beef - Ground Medium', '$2.08', 'incentivize dynamic infomediaries'],
    [252, 'Lobster - Baby, Boiled', '$4.39', 'redefine collaborative e-commerce'],
    [253, 'Wiberg Super Cure', '$8.59', 'optimize sticky networks'],
    [254, 'Urban Zen Drinks', '$7.70', 'disintermediate enterprise architectures'],
    [255, 'Artichoke - Fresh', '$8.67', 'enhance killer technologies'],
    [256, 'Soup Campbells', '$6.56', 'reinvent B2C models'],
    [257, 'Nantucket - Orange Mango Cktl', '$6.90', 'synthesize transparent ROI'],
    [258, 'Wine - Red, Harrow Estates, Cab', '$3.97', 'leverage e-business web services'],
    [259, 'Sour Puss - Tangerine', '$9.86', 'reinvent clicks-and-mortar initiatives'],
    [260, 'Nantucket - Carrot Orange', '$6.29', 'integrate sticky eyeballs'],
    [261, 'Clams - Littleneck, Whole', '$5.53', 'target viral e-commerce'],
    [262, 'Container - Clear 32 Oz', '$3.77', 'incubate magnetic deliverables'],
    [263, 'Curry Paste - Madras', '$4.25', 'drive 24/7 web-readiness'],
    [264, 'Crawfish', '$6.18', 'implement vertical partnerships'],
    [265, 'Nut - Cashews, Whole, Raw', '$9.77', 'transform sexy e-tailers'],
    [266, 'Herb Du Provence - Primerba', '$8.91', 'harness bleeding-edge deliverables'],
    [267, 'Wine - Two Oceans Sauvignon', '$5.52', 'reintermediate seamless platforms'],
    [268, 'Eggs - Extra Large', '$7.39', 'extend intuitive channels'],
    [269, 'Bread - Bagels, Plain', '$8.43', 'deliver one-to-one e-business'],
    [270, 'Limes', '$4.24', 'engineer open-source solutions'],
    [271, 'Mix - Cappucino Cocktail', '$2.12', 'implement best-of-breed web-readiness'],
    [272, 'Rice - 7 Grain Blend', '$2.01', 'synthesize collaborative networks'],
    [273, 'Juice - Happy Planet', '$9.41', 'transform rich portals'],
    [274, 'Veal - Liver', '$6.04', 'revolutionize customized content'],
    [275, 'Soup Campbells Turkey Veg.', '$2.84', 'e-enable sticky schemas'],
    [276, 'Bag Stand', '$1.63', 'deploy holistic ROI'],
    [277, 'Coconut - Whole', '$2.22', 'empower proactive users'],
    [278, 'Crab - Meat', '$9.03', 'reinvent bricks-and-clicks e-business'],
    [279, 'Yogurt - Strawberry, 175 Gr', '$8.51', 'morph holistic functionalities'],
    [280, 'Pork - Back, Long Cut, Boneless', '$6.09', 'empower collaborative networks'],
    [281, 'Vegetable - Base', '$3.82', 'orchestrate granular action-items'],
    [282, 'Puree - Kiwi', '$7.55', 'deploy dot-com paradigms'],
    [283, 'Hold Up Tool Storage Rack', '$7.37', 'deploy user-centric functionalities'],
    [284, 'Sobe - Cranberry Grapefruit', '$2.06', 'drive real-time e-services'],
    [285, 'Wine - Cotes Du Rhone Parallele', '$6.69', 'evolve next-generation portals'],
    [286, 'Melon - Watermelon Yellow', '$8.09', 'disintermediate cutting-edge infrastructures'],
    [287, 'Sauce - Sesame Thai Dressing', '$7.82', 'embrace clicks-and-mortar solutions'],
    [288, 'Swiss Chard', '$8.34', 'whiteboard web-enabled ROI'],
    [289, 'Pastry - Baked Scones - Mini', '$7.74', 'drive sticky functionalities'],
    [290, 'Greens Mustard', '$1.94', 'synthesize clicks-and-mortar e-tailers'],
    [291, 'Soda Water - Club Soda, 355 Ml', '$5.76', 'engineer rich relationships'],
    [292, 'Cape Capensis - Fillet', '$4.36', 'unleash integrated solutions'],
    [293, 'Beer - Paulaner Hefeweisse', '$9.78', 'cultivate mission-critical experiences'],
    [294, 'Cherries - Bing, Canned', '$4.24', 'visualize clicks-and-mortar bandwidth'],
    [295, 'Truffle Cups - Brown', '$5.43', 'monetize granular content'],
    [296, 'Wine - Acient Coast Caberne', '$9.46', 'brand e-business deliverables'],
    [297, 'Longan', '$9.05', 'deploy user-centric relationships'],
    [298, 'Icecream - Dstk Strw Chseck', '$8.47', 'reinvent seamless action-items'],
    [299, 'Potatoes - Peeled', '$6.69', 'incubate revolutionary mindshare'],
    [300, 'Pasta - Lasagne, Fresh', '$6.02', 'embrace ubiquitous methodologies'],
    [301, 'Garbage Bags - Clear', '$8.81', 'target virtual functionalities'],
    [302, 'Flavouring - Orange', '$5.51', 'synergize web-enabled e-markets'],
    [303, 'Cheese - Parmigiano Reggiano', '$6.59', 'maximize integrated infrastructures'],
    [304, 'Halibut - Whole, Fresh', '$9.84', 'maximize innovative functionalities'],
    [305, 'Latex Rubber Gloves Size 9', '$5.24', 'deploy world-class architectures'],
    [306, 'Veal - Provimi Inside', '$4.70', 'brand B2C e-commerce'],
    [307, 'Pork - Inside', '$3.23', 'reinvent distributed infrastructures'],
    [308, 'Salmon Steak - Cohoe 6 Oz', '$2.85', 'mesh seamless technologies'],
    [309, 'Garbage Bags - Black', '$4.07', 'maximize cross-media e-tailers'],
    [310, 'Beer - Camerons Auburn', '$3.99', 'unleash value-added paradigms'],
    [311, 'Wine - Cava Aria Estate Brut', '$8.87', 'e-enable vertical users'],
    [312, 'Pasta - Cannelloni, Sheets, Fresh', '$5.92', 'generate extensible platforms'],
    [313, 'Bread - White, Unsliced', '$8.82', 'maximize viral e-markets'],
    [314, 'Cleaner - Pine Sol', '$6.98', 'revolutionize plug-and-play e-services'],
    [315, 'Compound - Mocha', '$2.19', 'redefine dynamic deliverables'],
    [316, 'Bagels Poppyseed', '$7.47', 'extend compelling web-readiness'],
    [317, 'Tomato - Green', '$9.16', 'unleash compelling partnerships'],
    [318, 'Salmon Steak - Cohoe 8 Oz', '$4.59', 'monetize 24/365 deliverables'],
    [319, 'Mushroom - Oyster, Fresh', '$8.37', 'transform bleeding-edge methodologies'],
    [320, 'Bread - Triangle White', '$1.32', 'exploit value-added metrics'],
    [321, 'Extract - Almond', '$6.07', 'envisioneer sexy mindshare'],
    [322, 'Southern Comfort', '$5.59', 'enhance 24/7 web-readiness'],
    [323, 'Beer - Blue', '$6.50', 'transition magnetic applications'],
    [324, 'Seabream Whole Farmed', '$7.32', 'benchmark enterprise infrastructures'],
    [325, 'Gatorade - Fruit Punch', '$1.86', 'whiteboard ubiquitous web-readiness'],
    [326, 'Jerusalem Artichoke', '$6.67', 'utilize cross-platform channels'],
    [327, 'Sugar - Palm', '$8.35', 'revolutionize one-to-one methodologies'],
    [328, 'Veal - Brisket, Provimi, Bone - In', '$5.05', 'e-enable interactive portals'],
    [329, 'Wine - Merlot Vina Carmen', '$3.98', 'repurpose turn-key methodologies'],
    [330, 'Wild Boar - Tenderloin', '$7.63', 'benchmark synergistic infomediaries'],
    [331, 'Cheese - Camembert', '$3.96', 'aggregate dynamic action-items'],
    [332, 'Chocolate - Sugar Free Semi Choc', '$9.16', 'productize killer eyeballs'],
    [333, 'Bread - Corn Muffaleta Onion', '$3.64', 'whiteboard value-added schemas'],
    [334, 'Tuna - Fresh', '$2.39', 'redefine global channels'],
    [335, 'Wine - Ruffino Chianti', '$4.39', 'drive world-class e-tailers'],
    [336, 'Strawberries', '$8.08', 'target cross-platform markets'],
    [337, 'Juice - Apple Cider', '$9.04', 'iterate open-source action-items'],
    [338, 'Chocolate Bar - Oh Henry', '$6.97', 'aggregate magnetic niches'],
    [339, 'Buffalo - Short Rib Fresh', '$6.31', 'monetize 24/365 partnerships'],
    [340, 'Cauliflower', '$5.85', 'generate robust models'],
    [341, 'Veal - Provimi Inside', '$9.17', 'cultivate mission-critical applications'],
    [342, 'Crab - Dungeness, Whole, live', '$9.25', 'evolve plug-and-play methodologies'],
    [343, 'Bread - White Mini Epi', '$1.68', 'recontextualize granular metrics'],
    [344, 'Wine - Kwv Chenin Blanc South', '$6.12', 'facilitate dot-com infomediaries'],
    [345, 'Wine - Montecillo Rioja Crianza', '$6.14', 'innovate synergistic vortals'],
    [346, 'Pastry - Banana Muffin - Mini', '$2.71', 'e-enable global initiatives'],
    [347, 'Beef Ground Medium', '$8.33', 'iterate compelling initiatives'],
    [348, 'Garbag Bags - Black', '$5.36', 'cultivate 24/7 relationships'],
    [349, 'Fond - Chocolate', '$6.43', 'transition turn-key infrastructures'],
    [350, 'Pear - Packum', '$8.66', 'strategize B2B markets'],
    [351, 'Kellogs All Bran Bars', '$9.96', 'architect strategic markets'],
    [352, 'Oyster - In Shell', '$1.53', 'redefine leading-edge convergence'],
    [353, 'Duck - Fat', '$3.46', 'deploy dynamic vortals'],
    [354, 'Sauce Bbq Smokey', '$1.20', 'reintermediate plug-and-play relationships'],
    [355, 'Broom And Broom Rack White', '$5.49', 'integrate integrated synergies'],
    [356, 'Foam Espresso Cup Plain White', '$4.58', 'transform real-time functionalities'],
    [357, 'Tea - Black Currant', '$5.88', 'scale B2B action-items'],
    [358, 'Momiji Oroshi Chili Sauce', '$3.64', 'disintermediate distributed ROI'],
    [359, 'Turnip - White', '$2.74', 'extend web-enabled deliverables'],
    [360, 'Pork - Sausage Casing', '$8.39', 'engineer open-source niches'],
    [361, 'Bread - Kimel Stick Poly', '$8.78', 'transform transparent methodologies'],
    [362, 'Wine - Magnotta - Bel Paese White', '$5.36', 'innovate rich infomediaries'],
    [363, 'Artichokes - Jerusalem', '$7.78', 'visualize cross-media interfaces'],
    [364, 'Sterno - Chafing Dish Fuel', '$2.71', 'incubate turn-key models'],
    [365, 'Thyme - Dried', '$3.10', 'architect B2C interfaces'],
    [366, 'Cheese - Bocconcini', '$3.37', 'incubate next-generation partnerships'],
    [367, 'Pepsi - Diet, 355 Ml', '$7.06', 'iterate vertical communities'],
    [368, 'Spice - Peppercorn Melange', '$1.52', 'deploy efficient solutions'],
    [369, 'Milk - Buttermilk', '$2.62', 'recontextualize strategic networks'],
    [370, 'Beans - Long, Chinese', '$9.53', 'e-enable cross-platform web-readiness'],
    [371, 'Tomatoes - Hot House', '$9.56', 'maximize integrated e-business'],
    [372, 'Wine - Jafflin Bourgongone', '$3.20', 'synergize sexy relationships'],
    [373, 'Jolt Cola', '$8.74', 'strategize granular metrics'],
    [374, 'Pasta - Fettuccine, Egg, Fresh', '$5.56', 'enable front-end networks'],
    [375, 'Bananas', '$4.14', 'syndicate frictionless supply-chains'],
    [376, 'Liqueur Banana, Ramazzotti', '$8.05', 'enhance mission-critical relationships'],
    [377, 'Sponge Cake Mix - Chocolate', '$9.08', 'empower leading-edge initiatives'],
    [378, 'Basil - Pesto Sauce', '$1.96', 'visualize cutting-edge schemas'],
    [379, 'Extract - Rum', '$1.15', 'morph collaborative synergies'],
    [380, 'Wine - Soave Folonari', '$6.74', 'innovate back-end mindshare'],
    [381, 'Oregano - Dry, Rubbed', '$3.34', 'seize bleeding-edge relationships'],
    [382, 'Rice - Jasmine Sented', '$4.81', 'synergize intuitive infomediaries'],
    [383, 'Parsley - Dried', '$4.47', 'architect leading-edge relationships'],
    [384, 'Water, Tap', '$7.14', 'enhance front-end action-items'],
    [385, 'Pork - Ham, Virginia', '$2.47', 'mesh out-of-the-box experiences'],
    [386, 'Wine - Ej Gallo Sonoma', '$9.81', 'revolutionize value-added e-business'],
    [387, 'Muffin - Mix - Strawberry Rhubarb', '$1.62', 'recontextualize impactful users'],
    [388, 'Lettuce - Treviso', '$3.34', 'redefine enterprise content'],
    [389, 'Shrimp - Black Tiger 6 - 8', '$8.58', 'synthesize bleeding-edge models'],
    [390, 'Flavouring - Rum', '$4.07', 'harness seamless metrics'],
    [391, 'Shrimp - 21/25, Peel And Deviened', '$4.48', 'e-enable interactive communities'],
    [392, 'Cheese - Brie,danish', '$2.30', 'monetize B2C supply-chains'],
    [393, 'Dried Peach', '$1.94', 'morph wireless deliverables'],
    [394, 'Chocolate - Pistoles, White', '$1.82', 'cultivate impactful action-items'],
    [395, 'Lemon Balm - Fresh', '$5.33', 'orchestrate extensible action-items'],
    [396, 'Wine - Red, Cooking', '$6.06', 'optimize clicks-and-mortar portals'],
    [397, 'Cheese - Brie Roitelet', '$8.57', 'scale mission-critical communities'],
    [398, 'Turnip - White', '$9.88', 'transform enterprise methodologies'],
    [399, 'Yoplait - Strawbrasp Peac', '$8.43', 'reintermediate bleeding-edge channels'],
    [400, 'Yogurt - Banana, 175 Gr', '$3.41', 'orchestrate strategic vortals'],
    [401, 'Iced Tea - Lemon, 340ml', '$2.38', 'facilitate vertical infomediaries'],
    [402, 'Vegetable - Base', '$9.51', 'deploy back-end e-business'],
    [403, 'Oven Mitts - 15 Inch', '$4.87', 'architect visionary systems'],
    [404, 'Tia Maria', '$5.44', 'syndicate world-class bandwidth'],
    [405, 'Longos - Grilled Salmon With Bbq', '$5.29', 'innovate value-added architectures'],
    [406, 'Sugar - Individual Portions', '$8.49', 'incentivize sticky initiatives'],
    [407, 'Apple - Custard', '$2.50', 'deliver distributed platforms'],
    [408, 'Juice - Ocean Spray Kiwi', '$9.12', 'syndicate innovative mindshare'],
    [409, 'Tequila - Sauza Silver', '$3.94', 'transition 24/365 metrics'],
    [410, 'Appetizer - Seafood Assortment', '$7.91', 'incubate real-time convergence'],
    [411, 'Bread - White Epi Baguette', '$7.68', 'syndicate compelling mindshare'],
    [412, 'Foie Gras', '$5.16', 'evolve clicks-and-mortar functionalities'],
    [413, 'Roe - White Fish', '$6.08', 'cultivate holistic platforms'],
    [414, 'Wine - Bourgogne 2002, La', '$8.99', 'incentivize efficient infomediaries'],
    [415, 'Table Cloth - 53x69 Colour', '$4.83', 'leverage distributed action-items'],
    [416, 'Roe - White Fish', '$3.83', 'reintermediate ubiquitous e-business'],
    [417, 'Soup - Knorr, Veg / Beef', '$3.75', 'reinvent e-business mindshare'],
    [418, 'Vol Au Vents', '$7.32', 'maximize integrated mindshare'],
    [419, 'Energy Drink Bawls', '$6.70', 'leverage 24/365 networks'],
    [420, 'Lemon Tarts', '$6.02', 'revolutionize plug-and-play web services'],
    [421, 'Tofu - Soft', '$6.91', 'productize distributed methodologies'],
    [422, 'Soup Campbells Beef With Veg', '$7.49', 'deploy magnetic methodologies'],
    [423, 'Duck - Whole', '$7.69', 'harness wireless partnerships'],
    [424, 'Wine - Rioja Campo Viejo', '$2.70', 'maximize 24/7 networks'],
    [425, 'Banana - Leaves', '$5.26', 'extend ubiquitous channels'],
    [426, 'Pasta - Canelloni', '$3.02', 'exploit vertical schemas'],
    [427, 'Thyme - Fresh', '$1.33', 'transform dot-com methodologies'],
    [428, 'Clam - Cherrystone', '$7.02', 'transition bricks-and-clicks relationships'],
    [429, 'Water - Mineral, Natural', '$2.15', 'embrace out-of-the-box markets'],
    [430, 'Tomato - Green', '$5.60', 'utilize user-centric niches'],
    [431, 'Energy Drink - Redbull 355ml', '$7.95', 'visualize viral systems'],
    [432, 'Mix - Cappucino Cocktail', '$3.69', 'repurpose interactive web-readiness'],
    [433, 'Sugar - Sweet N Low, Individual', '$8.94', 'target value-added architectures'],
    [434, 'Bread - White, Unsliced', '$9.71', 'extend open-source systems'],
    [435, 'Oil - Olive', '$6.45', 'facilitate value-added platforms'],
    [436, 'Flower - Daisies', '$5.12', 'transition web-enabled portals'],
    [437, 'Cheese - Goat', '$5.98', 'recontextualize interactive markets'],
    [438, 'Honey - Liquid', '$5.44', 'cultivate intuitive e-services'],
    [439, 'Coriander - Seed', '$2.24', 'seize bricks-and-clicks methodologies'],
    [440, 'Butter Balls Salted', '$7.01', 'orchestrate distributed infomediaries'],
    [441, 'Fork - Plastic', '$5.61', 'facilitate rich e-services'],
    [442, 'Rosemary - Primerba, Paste', '$8.70', 'empower open-source schemas'],
    [443, 'Horseradish Root', '$5.82', 'engage synergistic markets'],
    [444, 'Lamb - Sausage Casings', '$7.47', 'recontextualize synergistic e-markets'],
    [445, 'Beer - Original Organic Lager', '$6.66', 'streamline collaborative solutions'],
    [446, 'Soup - Base Broth Beef', '$6.77', 'architect holistic solutions'],
    [447, 'Puree - Guava', '$9.59', 'engineer mission-critical methodologies'],
    [448, 'Cake - Box Window 10x10x2.5', '$7.38', 'architect end-to-end partnerships'],
    [449, 'Lettuce - Curly Endive', '$2.40', 'revolutionize intuitive functionalities'],
    [450, 'Olives - Morracan Dired', '$4.60', 'engineer global schemas'],
    [451, 'Mushroom - Porcini, Dry', '$1.20', 'iterate rich paradigms'],
    [452, 'Wasabi Powder', '$3.04', 'e-enable innovative web services'],
    [453, 'Plate Foam Laminated 9in Blk', '$1.15', 'transition viral niches'],
    [454, 'Icecream Bar - Del Monte', '$9.25', 'synergize dynamic initiatives'],
    [455, 'Turnip - Wax', '$6.42', 'redefine compelling platforms'],
    [456, 'Goat - Whole Cut', '$5.61', 'matrix cutting-edge schemas'],
    [457, 'Wine - Vovray Sec Domaine Huet', '$1.61', 'deploy one-to-one ROI'],
    [458, 'Beef - Eye Of Round', '$4.96', 'generate collaborative portals'],
    [459, 'Wine - Guy Sage Touraine', '$9.24', 'drive dynamic partnerships'],
    [460, 'Grouper - Fresh', '$6.29', 'incubate value-added methodologies'],
    [461, 'Bread - Malt', '$9.82', 'empower dot-com synergies'],
    [462, 'Shrimp - 21/25, Peel And Deviened', '$7.15', 'leverage vertical markets'],
    [463, 'Oil - Margarine', '$9.32', 'incentivize killer e-commerce'],
    [464, 'Figs', '$1.84', 'enhance one-to-one portals'],
    [465, 'Cocoa Powder - Natural', '$7.66', 'exploit impactful deliverables'],
    [466, 'Cleaner - Pine Sol', '$9.02', 'streamline bricks-and-clicks deliverables'],
    [467, 'Munchies Honey Sweet Trail Mix', '$3.52', 'repurpose synergistic niches'],
    [468, 'Irish Cream - Butterscotch', '$9.16', 'benchmark cross-platform interfaces'],
    [469, 'Octopus', '$4.21', 'synergize cross-platform metrics'],
    [470, 'Wine - Vovray Sec Domaine Huet', '$7.38', 'seize cross-platform e-tailers'],
    [471, 'Capers - Pickled', '$9.50', 'visualize integrated applications'],
    [472, 'Wine - Ej Gallo Sierra Valley', '$7.24', 'empower web-enabled channels'],
    [473, 'Triple Sec - Mcguinness', '$8.33', 'reinvent scalable infrastructures'],
    [474, 'Pants Custom Dry Clean', '$7.74', 'innovate dot-com networks'],
    [475, 'Yogurt - Cherry, 175 Gr', '$3.76', 'redefine collaborative niches'],
    [476, 'Red Currant Jelly', '$7.87', 'matrix global users'],
    [477, 'Lemon Balm - Fresh', '$4.28', 'seize enterprise ROI'],
    [478, 'Gelatine Leaves - Envelopes', '$4.51', 'extend dot-com infrastructures'],
    [479, 'Knife Plastic - White', '$6.48', 'incubate rich users'],
    [480, 'Wine - White, Riesling, Semi - Dry', '$2.37', 'incentivize bleeding-edge networks'],
    [481, 'Shrimp - Black Tiger 8 - 12', '$6.50', 'aggregate integrated e-markets'],
    [482, 'Wine - Red, Concha Y Toro', '$8.12', 'enable extensible synergies'],
    [483, 'Salt And Pepper Mix - Black', '$8.22', 'evolve killer web-readiness'],
    [484, 'The Pop Shoppe - Lime Rickey', '$5.39', 'streamline distributed e-business'],
    [485, 'Juice - Orange 1.89l', '$2.53', 'repurpose innovative e-business'],
    [486, 'Truffle Shells - White Chocolate', '$3.46', 'matrix synergistic solutions'],
    [487, 'Bar Mix - Lemon', '$1.93', 'monetize enterprise applications'],
    [488, 'Thyme - Fresh', '$1.41', 'revolutionize killer markets'],
    [489, 'Cheese - Brie', '$1.42', 'matrix best-of-breed communities'],
    [490, 'Sugar - Cubes', '$10.00', 'extend one-to-one initiatives'],
    [491, 'Pineapple - Canned, Rings', '$4.11', 'e-enable rich mindshare'],
    [492, 'Water - San Pellegrino', '$8.23', 'facilitate turn-key deliverables'],
    [493, 'Appetizer - Cheese Bites', '$7.67', 'repurpose end-to-end architectures'],
    [494, 'Hot Chocolate - Individual', '$2.01', 'reintermediate seamless communities'],
    [495, 'Lemon Grass', '$5.16', 'transition impactful infrastructures'],
    [496, 'Sauce - Salsa', '$8.77', 'implement global infrastructures'],
    [497, 'Wine - Acient Coast Caberne', '$7.62', 'extend strategic platforms'],
    [498, 'Turkey - Ground. Lean', '$9.04', 'orchestrate rich e-tailers'],
    [499, 'Olives - Stuffed', '$2.65', 'embrace next-generation infomediaries'],
    [500, 'Kippers - Smoked', '$1.58', 'aggregate world-class vortals']
]

product_list.each do |id, name, price, description|
    Product.create(id: id, name: name, price: price, description: description)
end